---
kind: pipeline
name: go-latest

steps:
  - name: test
    image: golang:latest
    commands:
      - export GOPROXY=https://goproxy.io
      - go version
      - go test -v .
      - go vet

---
kind: pipeline
name: go-1-12

steps:
  - name: test
    image: golang:1.12.1
    commands:
      - export GOPROXY=https://goproxy.io
      - go version
      - go test -v .
      - go vet
